services:
  frontend:
    build:
      context: ./frontend/evsync
      dockerfile: ../Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/evsync:/app
    environment:
      - NODE_ENV=development


  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE:   mydb
      MYSQL_USER:       myuser
      MYSQL_PASSWORD:   mypass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
  
  backend:
    build: 
      context: ./backend       
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
        mysql:
          condition: service_healthy

volumes:
  mysql-data:
    